_BASE_: Base-COCO-InstanceSegmentation.yaml
DATASETS:
  TRAIN: ("coco_zsi_48_17_train",)
  TEST: ("coco_zsi_48_17_val",)
SOLVER:
  IMS_PER_BATCH: 12
  BASE_LR: 0.001
  GENERATOR_LR: 5e-4
  MAX_ITER: 4000
  CHECKPOINT_PERIOD: 2000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAM"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: False
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
MODEL:
  META_ARCHITECTURE: "PADing"
  SEM_SEG_HEAD:
    NAME: "MaskFormerHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 65
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    # pixel decoder
    PIXEL_DECODER_NAME: "MSDeformAttnPixelDecoder"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
  MASK_FORMER:
    TRANS_NUM_LAYER: 3
    TRANS_MEMORY_NUM_QUERY: 400
    VEC_PATH: 'embeddings/coco/word_w2v_withbg_48_17.txt'
    STRUCTURE_WEIGHT: 0.001
    DROP_OUT_ED: 0.1
    CLASS_ECO: 2.0
    NUM_CHOOSE: 5
    WEIGHT_1: 1.0
    WEIGHT_2: 1.0
    WEIGHT_3: 0.5

    TRANSFORMER_DECODER_NAME: "MultiScaleMaskedTransformerDecoder"
    TRANSFORMER_IN_FEATURE: "multi_scale_pixel_decoder"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 10  # 9 decoder layers, add one for the loss on learnable query
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: True
      PANOPTIC_ON: False

      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
TEST:
  EVAL_PERIOD: 2000
OUTPUT_DIR: 'PADing_instance'
INPUT:
  IMAGE_SIZE: 960